<?php
$totalcountrow = 1;
$nooftrax = 1;
$startdate = strtotime("now");
$totalvalue = 0.00;
$arrayfetch  = array();
$explode  = explode("\r\n",$body);
foreach ($explode as $rowkey => $rowelement):
	$counter = 1;
	if($rowelement!=""){
		$columnelement = explode(",",$rowelement);
		foreach($columnelement as  $keycolumn => $columnvalue):
			$arrayfetch[$keycolumn] = str_replace('"',"",$columnvalue);
		endforeach;
		$totalvalue += $arrayfetch[5];
		
		/*
			Generate Record ID 0 Header banner List
		*/
		
		print $arrayfetch[0].",".$arrayfetch[1].",".$arrayfetch[2].",0,0,0,0,".$arrayfetch[5].",".$arrayfetch[5].",".$arrayfetch[5].",1,".$arrayfetch[15].",0,0,".$arrayfetch[9]."\r\n";
		$totalcountrow++;
		
		/*
			Generate Record ID 1 List
		*/
		$resultsql = db_query("SELECT uc_order_products.model AS uc_order_products_model, 
			uc_order_products.qty AS uc_order_products_qty, 
			uc_order_products.price AS uc_products_sell_price, 
			uc_orders.order_id  AS uc_order_id, 
			node.nid AS node_nid 
			FROM {uc_order_products} uc_order_products 
			LEFT JOIN {uc_orders} uc_orders ON uc_order_products.order_id = uc_orders.order_id 
			LEFT JOIN {node} node ON uc_order_products.nid = node.nid 
			WHERE uc_orders.order_id = :oid",array(':oid' => $arrayfetch[1]));
			
        if($resultsql->rowCount()>0){ 
			foreach ($resultsql as $record) {
				$nodeload = node_load($record->node_nid);
				$orderinfo = uc_order_load($record->uc_order_id);
				print $arrayfetch[0].",".$arrayfetch[1].",".$arrayfetch[2].","."1,";
				//print $record->uc_order_products_model.",";
				print (isset($nodeload->field_barcode['und'][0]['value']))?$nodeload->field_barcode['und'][0]['value']:0;
				print ",";
				print $record->uc_order_products_qty.",";
				print number_format($record->uc_products_sell_price,2,".","").",";
				print number_format(($record->uc_products_sell_price * $record->uc_order_products_qty),2,".","").",";
				print "1,0,0,0,0,0,0,0,0"."\r\n";
				//print $record->uc_order_products_model.",";
				$totalcountrow++;
				$nooftrax++;
			}
		}
		/*
			shipping total 
		*/
		$dbquerysearchprice = db_query("SELECT uc_order_products.qty AS uc_order_products_qty, uc_order_products.price AS uc_products_sell_price 
		FROM {uc_order_products} uc_order_products 
		LEFT JOIN {uc_orders} uc_orders ON uc_order_products.order_id = uc_orders.order_id WHERE uc_order_products.order_id = :oid",array(':oid' => $arrayfetch[1]));
		if($dbquerysearchprice->rowCount()>0){ 
			$totalitem = 0;
			foreach ($dbquerysearchprice as $record)
				$totalitem += $record->uc_products_sell_price * $record->uc_order_products_qty;

			print $arrayfetch[0].",".$arrayfetch[1].",".$arrayfetch[2].","."1,";
			print "9019,1,";
			print number_format(($arrayfetch[5]-$totalitem),2,".","").",";
			print number_format(($arrayfetch[5]-$totalitem),2,".","").",";
			print "1,0,0,0,0,0,0,0,0"."\r\n";
		}
		
		/*
			Generate Record Id 2
		*/
		foreach($columnelement as  $keycolumn => $columnvalue):
			if($keycolumn<15){
				if($keycolumn == 9)
					print "0,"; // THIS IS FOR SALES INVOICE GENERATED BY BANK FOR NOW NULL
				else
					print $columnvalue.",";
			}	
		endforeach;		
		print "\r\n";
		$totalcountrow++;
		/*
			record ID 3 for discount pending
		
		*/
		//print $arrayfetch[0].",".$arrayfetch[1].",".$arrayfetch[2].",3,0,0,0,0,0,0,0,0,0\r\n";
	}
endforeach;
$enddate = strtotime("now");
if(isset($_GET['typecron_check'])){
	$nid = db_insert('z_report_logs')->fields(array(
		'filename' => "C0370423".date("mdy",strtotime($_GET['created']['value']['date'])).".zip",
		'start_datetime' => $startdate,
		'end_datetime' => $enddate,
		'totalcount'=>($totalcountrow-1),
		'totalamount'=>$totalvalue,
		'batchamount'=>$totalvalue,
		'nooftrx'=>($nooftrax-1),
		'totaltrxammount'=>$totalvalue,
		'notrxlines'=>($totalcountrow-1)
	))->execute();
}

?>
