<?php
$totalcountrow = 1;
$nooftrax = 1;
$startdate = strtotime(date($_GET['created']['value']['date']." H:i:s"));
//$startdate = strtotime("2012-01-04 12:01:00");
$totalvalue = 0.00;
$arrayfetch  = array();
$explode  = explode("\r\n",$body);
foreach ($explode as $rowkey => $rowelement):
	$counter = 1;
	if($rowelement!=""){
		$columnelement = explode(",",$rowelement);
		foreach($columnelement as  $keycolumn => $columnvalue):
			$arrayfetch[$keycolumn] = str_replace('"',"",$columnvalue);
		endforeach;
		$totalvalue += $arrayfetch[5];
		
		/*
			Generate Record ID 0 Header banner List
		*/
		
		print $arrayfetch[0].",".$arrayfetch[1].",".$arrayfetch[2].",0,0,0,0,".$arrayfetch[5].",".$arrayfetch[5].",".$arrayfetch[5].",1,".$arrayfetch[15].",0,0,".$arrayfetch[9]."\r\n";
		$nooftrax++;
		$totalcountrow++;
		
		/*
			Generate Record ID 1 List
		*/
		$resultsql = db_query("SELECT 
			uc_order_products.model AS uc_order_products_model, 
			uc_order_products.qty AS uc_order_products_qty, 
			uc_order_products.price AS uc_products_sell_price, 
			uc_orders.order_id  AS uc_order_id, 
			node.nid AS node_nid 
			FROM {uc_order_products} uc_order_products 
			LEFT JOIN {uc_orders} uc_orders ON uc_order_products.order_id = uc_orders.order_id 
			LEFT JOIN {node} node ON uc_order_products.nid = node.nid 
			WHERE uc_orders.order_id = :oid",array(':oid' => $arrayfetch[1]));
			
        if($resultsql->rowCount()>0){ 
			foreach ($resultsql as $record) {
				$nodeload = node_load($record->node_nid);
				$orderinfo = uc_order_load($record->uc_order_id);
				print $arrayfetch[0].",".$arrayfetch[1].",".$arrayfetch[2].","."1,";
				//print $record->uc_order_products_model.",";
				print (isset($nodeload->field_barcode['und'][0]['value']))?$nodeload->field_barcode['und'][0]['value']:0;
				print ",";
				print $record->uc_order_products_qty.",";
				print number_format($record->uc_products_sell_price,2,".","").",";
				print number_format(($record->uc_products_sell_price * $record->uc_order_products_qty),2,".","").",";
				print "1,0,0,0,0,0,0,0,0"."\r\n";
				//print $record->uc_order_products_model.",";
				$totalcountrow++;
				
			}
		}
		/*
			shipping total 
		*/
		/*
		"SELECT 
		uc_order_products.qty AS uc_order_products_qty, 
		uc_order_products.price AS uc_products_sell_price
		FROM {uc_order_products} uc_order_products 
		LEFT JOIN {uc_orders} uc_orders ON uc_order_products.order_id = uc_orders.order_id 
		LEFT JOIN {sandcart_saci_delivery} sandcart_saci_delivery ON sandcart_saci_delivery.order_id = uc_orders.order_id 
		WHERE uc_order_products.order_id = :oid"
		$totalitem = 0;
		foreach ($dbquerysearchprice as $record)
				$totalitem += $record->uc_products_sell_price * $record->uc_order_products_qty;
				print $arrayfetch[0].",".$arrayfetch[1].",".$arrayfetch[2].","."1,";
			print "9019,1,";
			print number_format(($arrayfetch[5]-$totalitem),2,".","").",";
			print number_format(($arrayfetch[5]-$totalitem),2,".","").",";
			print "1,0,0,0,0,0,0,0,0"."\r\n";
		*/
		$dbquerysearchprice = db_select("sandcart_saci_delivery","scd")
		->fields("scd")
		->condition("scd.order_id",$arrayfetch[1])
		->execute();
		if($dbquerysearchprice->rowCount()>0){ 
			$ratefetch = $dbquerysearchprice->fetchObject();
			print $arrayfetch[0].",".$arrayfetch[1].",".$arrayfetch[2].","."1,";
			print "9033,1,";
			print number_format($ratefetch->frate,2,".","").",";
			print number_format($ratefetch->frate,2,".","").",";
			print "1,0,0,0,0,0,0,0,0"."\r\n";
			$totalcountrow++;
			if($ratefetch->vcharge>0){
				print $arrayfetch[0].",".$arrayfetch[1].",".$arrayfetch[2].","."1,";
				print "9034,1,";
				print number_format($ratefetch->vcharge,2,".","").",";
				print number_format($ratefetch->vcharge,2,".","").",";
				print "1,0,0,0,0,0,0,0,0"."\r\n";
				$totalcountrow++;
			}
			
		}
		/*
			Generate Record Id 2
		*/
		$orderinfo = uc_order_load($arrayfetch[1]);
		
		if($orderinfo->payment_method=="hsbc_migs"){
			$authorization_number = db_query("SELECT authorized_no FROM uc_hsbc_migs WHERE order_id = :oid",array(':oid' => $arrayfetch[1]))->fetchField();
			
			print $arrayfetch[0].",".$arrayfetch[1].",".$arrayfetch[2].",2,9,".$arrayfetch[5].",0,0,0,0,0,0,".$authorization_number.",0,1";	
			/*
			foreach($columnelement as  $keycolumn => $columnvalue):
				if($keycolumn<15){
					if($keycolumn == 9)
						print "0,"; // THIS IS FOR SALES INVOICE GENERATED BY BANK FOR NOW NULL
					else if($keycolumn == 14)
						print $columnvalue;
					else
						print $columnvalue.",";
				}	
			endforeach;
			*/
			
		}else{
			$bdo_cdv = db_select("sandcart_payment_bdo","spo")->fields('spo',array('bdo_cdv'))->condition('spo.order_id',$arrayfetch[1])->execute()->fetchfield();
			print $arrayfetch[0].",".$arrayfetch[1].",".$arrayfetch[2].",2,5,".$arrayfetch[9].",".$bdo_cdv.",9000110000,0,0,0,0,0,0,6";	
		}
		print "\r\n";
		
		
		$totalcountrow++;
		/*
			record ID 3 for discount pending
		
		*/
		//print $arrayfetch[0].",".$arrayfetch[1].",".$arrayfetch[2].",3,0,0,0,0,0,0,0,0,0\r\n";
	}

endforeach;
//$enddate = strtotime("2012-01-04 12:02:00");
$enddate = strtotime(date($_GET['created']['value']['date']." H:i:s"));
if(isset($_GET['typecron_check'])){
	$filename = "C0370423".date("mdy",strtotime($_GET['created']['value']['date'])).".zip";
	$result = db_query('SELECT transaction_batch_id FROM {z_report_logs} WHERE filename = :filename', array(':filename' => $filename));
	$arrainsertparams = 	array('filename' =>$filename ,'start_datetime' => $startdate,'end_datetime' => $enddate,'totalcount'=>($totalcountrow-1),'totalamount'=>$totalvalue,'batchamount'=>$totalvalue,'nooftrx'=>($nooftrax-1),'totaltrxammount'=>$totalvalue,'notrxlines'=>($totalcountrow-1));
	if($result->rowCount()>0){
		$transid = $result->fetchObject();
		$nid = db_update('z_report_logs')->fields($arrainsertparams)->condition('transaction_batch_id',$transid->transaction_batch_id)->execute();
	}else {
		$nid = db_insert('z_report_logs')->fields($arrainsertparams)->execute();
	}
}

?>

